# Generated by Django 5.2.4 on 2025-07-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('titulo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=30)),
                ('ano', models.TextField()),
            ],
            options={
                'db_table': 'filmes',
                'managed': False,
            },
        ),
    ]
