"""
Django settings for dsocial project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4uf!z8c=-5+(k_3(&bd&^ff9cg-!u7q&h@+p_nu$alue!l+m4&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1'] #27 Servidor


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4', #27 Instalação do Bootstrap
    'social_django', #27 Instalação do Social Auth
    'core', #27 Instalação do Core
    'django_extensions',  # habilita runserver_plus
]

MIDDLEWARE = [
    'social_django.middleware.SocialAuthExceptionMiddleware', #27 Instalação do Social Auth
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dsocial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'], #27 pasta templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends', #27 Autenticação
                'social_django.context_processors.login_redirect', #27 Autenticação
            ],
        },
    },
]

WSGI_APPLICATION = 'dsocial.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'pt-br' #27 Altera o idioma

TIME_ZONE = 'America/Sao_Paulo' #27 Altera o fuso horário

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# Configurações do Social Auth
AUTHENTICATION_BACKENDS = [
    'social_core.backends.facebook.FacebookOAuth2', #27 Autenticação login Facebook
    'django.contrib.auth.backends.ModelBackend', #27 Autenticação login Django
]
# Configurações de Autenticação para rotas "views.py"
LOGIN_URL = 'login' #27 Para onde mandar usuários não logados.
LOGIN_REDIRECT_URL = 'index' #27 Para onde mandar o usuário após login.
LOGOUT_URL = 'logout' #27 URL usada para fazer logout.
LOGOUT_REDIRECT_URL = 'login' #27 Para onde mandar o usuário após logout.

#27 Quando ocorre um erro durante o login social (falha ao autenticar)
SOCIAL_AUTH_RAISE_EXCEPTIONS = False  

from dotenv import load_dotenv 
import os

load_dotenv(os.path.join(BASE_DIR, '.env'))

CHAVE_IP = os.getenv('ID_aplicativo')
CHAVE_SECRETA = os.getenv('chave_secreta')

# Configurações para Facebook
SOCIAL_AUTH_FACEBOOK_KEY = CHAVE_IP
SOCIAL_AUTH_FACEBOOK_SECRET = CHAVE_SECRETA
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email', 'user_link']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id, name, email, picture.type(large), link'
}
SOCIAL_AUTH_FACEBOOK_EXTRA_DATA = [
    ('name', 'name'),
    ('email', 'email'),
    ('picture', 'picture'),
    ('link', 'profile_url'),
]
