"""
Django settings for banco project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1ex8(_8eben3!$81h$tdojujaa#-#hmn_#(15&c4l*lkkibxi$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] #33 Permitindo acesso local


# Application definition

INSTALLED_APPS = [
    'core', #33 Aplicação core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'banco.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'], #33 pasta templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'banco.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


from dotenv import load_dotenv 
import os

load_dotenv(os.path.join(BASE_DIR, '.env'))

ENGINE = os.getenv('engine')
NOME_DO_BANCO = os.getenv('nome_do_banco')
MEU_USUARIO = os.getenv('meu_usuario')
MINHA_SENHA = os.getenv('minha_senha')
PORTA = os.getenv('porta')

DATABASES = {
    'default': {
        'ENGINE': ENGINE,  #33 Usando PostgreSQL como banco de dados
        'NAME': NOME_DO_BANCO,  #33 Nome do banco de dados
        'USER': MEU_USUARIO,  #33 Usuário do banco de dados
        'PASSWORD': MINHA_SENHA,  #33 Senha do usuário do banco de dados
        'HOST': 'localhost',  #33 Host do banco de dados 
        'PORT': PORTA,  #33 Porta do banco de dados   
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br' #33  pt-br

TIME_ZONE = 'America/Sao_Paulo' #33 America/Sao_Paulo

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' #33 Diretório para arquivos estáticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' #33 Configuração para servir arquivos estáticos em produção 
MEDIA_URL = 'media/'  #33 URL para arquivos de mídia
MEDIA_ROOT = BASE_DIR / 'media'  #33 Diretório para arquivos de mídia

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#11 Configuração para servir arquivos de mídia (Django Admin)
LOGOUT_REDIRECT_URL = 'admin/login/'  #33 Redirecionar para a página inicial após logout
