"""
Django settings for seguranca project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5g1-3$sck-5-^o0h)b_#i!et!!yvs(az_bzh_-_fkmh5el@f(d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] #26 localhost


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'seguranca.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'], #26 pasta templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'seguranca.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'pt-br' #26 pt-br

TIME_ZONE = 'America/Sao_Paulo' #26 America/Sao_Paulo

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/' #26 media
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') #26 pasta static
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') #26 pasta media

###### Recursos Extras de Segurança do Django ######
# Força os navegadores a acessarem o site apenas via HTTPS durante o tempo definido (em segundos).
SECURE_HSTS_SECONDS = True
# Protege inclusive sub.dominio.com para evitar ataques downgrade em subdomínios.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# Evita ataques de MIME-sniffing, onde o navegador tenta adivinhar o tipo de arquivo.
SECURE_CONTENT_TYPE_NOSNIFF = True
# Protege contra ataques de Cross-Site-Scripting (XSS) e Ajuda a bloquear ataques Cross-site Scripting
SECURE_BROWSER_XSS_FILTER = True
# Protege contra ataques de Cross-Site-Request-Forging (CSRF), somente envio de conexão HTTPS.
SESSION_COOKIE_SECURE = True
# Protege contra ataques de Cross-Site-Request-Forging (CSRF), somente envio de conexão HTTPS.
CSRF_COOKIE_SECURE = True
# Impede que JavaScript acesse o cookie CSRF e protege contra roubos de cookie via XSS.
CSRF_COOKIE_HTTPONLY = True
# Impede que o site seja carregado dentro de um iframe, protege contra clickjacking.
X_FRAME_OPTIONS = 'DENY'

# redireciona automaticamente todas as requisições HTTP para HTTPS, impossibilitando uso local da aplicação.
# SECURE_SSL_REDIRECT = True
