# Generated by Django 5.2.4 on 2025-07-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190919_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(help_text='Máximo de 30 caracteres', max_length=30, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='chassi',
            name='numero',
            field=models.CharField(help_text='Máximo de 16 caracteres', max_length=16, verbose_name='Chassi'),
        ),
    ]
