"""
Django settings for projeto_03 project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&8@zy_&*q01-0cmv+@16^bdcjbm*av=la9qj%rr%=02tc=7&e='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#13 Permitindo acesso local para desenvolvimento em DEBUG=False
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  #13 Adicionando a aplicação core
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projeto_03.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],  #13 Diretório para templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projeto_03.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

from dotenv import load_dotenv 
import os

load_dotenv(os.path.join(BASE_DIR, '.env'))

ENGINE = os.getenv('engine')
NOME_DO_BANCO = os.getenv('nome_do_banco')
MEU_USUARIO = os.getenv('meu_usuario')
MINHA_SENHA = os.getenv('minha_senha')
PORTA = os.getenv('porta')

DATABASES = {
    'default': {
        'ENGINE': ENGINE,  #13 Usando PostgreSQL como banco de dados
        'NAME': NOME_DO_BANCO,  #13 Nome do banco de dados
        'USER': MEU_USUARIO,  #13 Usuário do banco de dados
        'PASSWORD': MINHA_SENHA,  #13 Senha do usuário do banco de dados
        'HOST': 'localhost',  #13 Host do banco de dados 
        'PORT': PORTA,  #13 Porta do banco de dados   
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br' #13 Definindo o idioma para português do Brasil

TIME_ZONE = 'America/Sao_Paulo' #13 Definindo o fuso horário para São Paulo

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/' #13 URL para arquivos de mídia
STATIC_ROOT = BASE_DIR / 'staticfiles'  #13 Diretório para arquivos estáticos
MEDIA_ROOT = BASE_DIR / 'media'  #13 Diretório para arquivos de mídia

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGOUT_REDIRECT_URL = 'index' #13 Redirecionamento após logout